"""Initial migration

Revision ID: 848195252e7e
Revises: 
Create Date: 2026-07-14 18:35:46.534885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '848195252e7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage',
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sessions_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('specsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_spec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_sections', sa.JSON(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('revised_spec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('parsing', 'critiquing', 'synthesizing', 'done', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specsession')
    op.drop_table('daily_usage')
    # ### end Alembic commands ###
